baseURL = 'http://mc-modding.vercel.app/'
languageCode = 'hu-hu'
title = 'Minecraft Modding'
theme = "hugo-theme-relearn"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
themeVariant = "relearn-dark"
swaggerInitialize = "{ \"theme\": \"dark\" }"
landingPageName = "<i class='fas fa-home'></i> Kezdőlap"

